# Generated by Django 5.0.2 on 2024-04-10 10:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название спектакля')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('is_premiere', models.BooleanField(default=False, verbose_name='Премьера')),
                ('duration_in_of_the_performance', models.TextField(blank=True, default='', verbose_name='Длительность')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('age_limit', models.CharField(max_length=5, verbose_name='Возрастное ограничения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('PAYED', 'Оплачен'), ('IN_PROGRESS', 'В обработке'), ('CANCELED', 'Отменен')], default='CREATED', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата и время показа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за билет')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена без скидки(зачеркнуто)')),
                ('count', models.IntegerField(default=0, verbose_name='Количество билетов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.performance', verbose_name='Билет спектакля')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за билет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Заказанный билет',
                'verbose_name_plural': 'Заказанные билеты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='main.OrderProduct', to='main.product', verbose_name='Билеты'),
        ),
    ]
