# Generated by Django 5.0.3 on 2024-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='stage_director',
            field=models.CharField(default='', max_length=255, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='duration_in_of_the_performance',
            field=models.CharField(max_length=255, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='premiere',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Премьера спектакля состоялась'),
        ),
    ]
