# Generated by Django 5.0.3 on 2024-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticket_delete_tiket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена без скидки(зачеркнуто)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='age_limit',
            field=models.CharField(max_length=3, verbose_name='Возрастное ограничения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за билет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название спектакля'),
        ),
    ]
