# Generated by Django 5.0.2 on 2024-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_performance_stage_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='update_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='performance',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена без скидки(зачеркнутое)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='category',
            field=models.ManyToManyField(to='main.categories', verbose_name='Категория'),
        ),
    ]
