# Generated by Django 5.0.2 on 2024-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_ticket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration_in_minutes',
            field=models.TextField(blank=True, default='', verbose_name='Длительность'),
        ),
    ]
