# Generated by Django 5.0.3 on 2024-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='main.OrderProduct', to='main.product', verbose_name='Билеты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PAYED', 'Оплачен'), ('IN_PROGRESS', 'В обработке'), ('DELIVERING', 'Доставляется'), ('DELIVERED', 'Доставлен'), ('CANCELED', 'Отменен')], default='CREATED', max_length=15, verbose_name='Статус'),
        ),
    ]
