# Generated by Django 5.0.3 on 2024-04-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_options_alter_order_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_activ',
            new_name='is_active',
        ),
    ]
