# Generated by Django 5.0.3 on 2024-04-03 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_is_activ_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата и время показа'),
        ),
    ]
