# Generated by Django 5.0.2 on 2024-04-04 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_show_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название спектакля')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('show_date', models.DateTimeField(default=datetime.date.today, verbose_name='Дата и время показа')),
                ('duration_in_of_the_performance', models.TextField(blank=True, default='', verbose_name='Длительность')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('age_limit', models.CharField(max_length=5, verbose_name='Возрастное ограничения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='duration_in_of_the_performance',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PAYED', 'Оплачен'), ('IN_PROGRESS', 'В обработке'), ('CANCELED', 'Отменен')], default='CREATED', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название билета'),
        ),
    ]
