# Generated by Django 5.0.3 on 2024-04-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_play_performance_remove_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='performance',
        ),
    ]
