# Generated by Django 5.0.3 on 2024-04-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
