# Generated by Django 5.0.2 on 2024-04-06 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='show_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='show_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата и время показа'),
        ),
    ]
