# Generated by Django 5.0.2 on 2024-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_performance_show_date_alter_product_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='is_premiere',
            field=models.BooleanField(default=False, verbose_name='Премьера'),
        ),
    ]
